version: "3"

services:
  task-service:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 8085:8085
    environment:
      APP_ENV: production
    networks:
      go-ms-examle:
        ipv4_address: 192.168.0.10

networks:
  go-ms-examle:
    external: true
