version: "3"

services:
  db:
    image: postgres:14.2-alpine
    container_name: auth_db
    restart: always
    environment:
      POSTGRES_USER: go
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: auth
    ports:
      - 5430:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
