version: "3"

services:
  project-service:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 8083:8083
    environment:
      APP_ENV: dev
    networks:
      go-microservices-examle:
        ipv4_address: 192.168.0.10

networks:
  go-microservices-examle:
    external: true
